---
- :name: cert
  :type: alert
  :url: 'https://www.us-cert.gov/ncas/alerts.xml'
- :name: dark reading
  :type: alert
  :url: 'http://www.darkreading.com/rss_simple.asp'
- :name: nvd
  :type: alert
  :url: 'https://nvd.nist.gov/download/nvd-rss.xml'
- :name: drupal core
  :type: alert
  :url: 'https://www.drupal.org/security/rss.xml/core/rss.xml'
- :name: drupal contrib
  :type: alert
  :url: 'https://www.drupal.org/security/contrib/rss.xml'

- :name: sans
  :type: news
  :url: 'https://isc.sans.edu/rssfeed.xml'
- :name: threatpost
  :type: news
  :url: 'http://threatpost.com/feed'
- :name: eff
  :type: news
  :url: 'https://www.eff.org/rss/updates.xml'
- :name: slashdot yro
  :type: news
  :url: 'http://rss.slashdot.org/Slashdot/slashdotYourRightsOnline'
- :name: net-security
  :type: news
  :url: 'https://feeds2.feedburner.com/HelpNetSecurity'

- :name: cisco
  :type: vendor
  :url: 'http://tools.cisco.com/security/center/psirtrss20/CiscoSecurityAdvisory.xml'
- :name: aws
  :type: vendor
  :url: 'https://alas.aws.amazon.com/alas.rss'
- :name: suse
  :type: vendor
  :url: 'http://www.novell.com/newsfeeds/rss/patches/security_notifications-daily.xml'

- :name: krebs
  :type: blog
  :url: 'http://krebsonsecurity.com/feed/'
