---
- :name: cert
  :type: alert
  :url: 'https://www.us-cert.gov/ncas/alerts.xml'
- :name: nvd
  :type: alert
  :url: 'https://nvd.nist.gov/download/nvd-rss.xml'
- :name: ibm
  :type: alert
  :url: 'http://www.iss.net/rss.php'

- :name: sans
  :type: news
  :url: 'https://isc.sans.edu/rssfeed.xml'
- :name: threatpost
  :type: news
  :url: 'http://threatpost.com/feed'
- :name: eff
  :type: news
  :url: 'https://www.eff.org/rss/updates.xml'
- :name: slashdot yro
  :type: news
  :url: 'http://rss.slashdot.org/Slashdot/slashdotYourRightsOnline'

- :name: cisco
  :type: vendor
  :url: 'http://tools.cisco.com/security/center/psirtrss20/CiscoSecurityAdvisory.xml'
- :name: aws
  :type: vendor
  :url: 'https://alas.aws.amazon.com/alas.rss'
- :name: ibm 
  :type: vendor
  :url: 'http://www.iss.net/rss.php'
- :name: suse
  :type: vendor
  :url: 'http://www.novell.com/newsfeeds/rss/patches/security_notifications-daily.xml'

- :name: krebs
  :type: blog
  :url: 'http://krebsonsecurity.com/feed/'

